name: '@g3ngar/mega-put'
description: 'Upload stuff to MEGA'
author: 'g3ngar'
inputs:
  mega_username:
    required: true
    description: 'MEGA email'
  mega_password:
    required: true
    description: 'MEGA password'
  path:
    required: true
    description: 'File or directory to upload'
  remote:
    required: true
    description: 'Name of the .tar file in MEGA where the uploaded content will be. Note this will be in the root directory.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'red'